# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

investors:
  -
    name: "Exnetwork"
    description: "Exnetwork Capital was founded in 2018 as a means to democratize access to opportunities to support blockchain projects."
    path: "assets/images/investors/exnetwork.png"
  -
    name: "Wave Capital"
    description: "An early-stage venture firm focused on marketplace businesses"
    path: "assets/images/investors/wave.png"
  -
    name: "Hot Dao"
    description: "Investor, VC fund & Incubator dedicated to the development of decentralized projects."
    path: "assets/images/investors/hotdao.png"
  -
    name: "Lotus Capital"
    description: "The Leading Crypto Fund in the Middle East, An ecosystem of entrepreneurs, engineers, researchers and academics"
    path: "assets/images/investors/lotus.png"
  -
    name: "CryptoDormFund"
    description: "The Leading College Crypto Network"
    path: "assets/images/investors/cryptodorm.png"
  -
    name: "Collin Star investment"
    description: "In early 2015. Ryan and other co-founders of the firm believed they could set a new benchmark for asset management fund performance through investment in Blockchain technology."
    path: "assets/images/investors/collin.png"
  -
    name: "Bixin venture"
    description: "Bixin Ventures invests in early-stage infrastructure projects that cultivate and facilitate mass adoption of open finance through permissionless and decentralized networks."
    path: "assets/images/investors/bixin.png"
  -
    name: "Water drip capital"
    description: "Waterdrip Capital was founded in 2017 by the most forward-thinking Chinese blockchain pioneers. It is an international investment institution focusing on blockchain industry."
    path: "assets/images/investors/waterdrip.png"
  -
    name: "Spark Digital Capital"
    description: "A research focused crypto fund that invests in the future of blockchain and tech"
    path: "assets/images/investors/spark.png"

press:
  - path: "assets/images/press/blockbeats.png"
  - path: "assets/images/press/wublockchain.png"
  - path: "assets/images/press/lefigaro.png"
  - path: "assets/images/press/hype.png"
  - path: "assets/images/press/forbes.png"